org: williamdnts
service: foodiary-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs24.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment: ${file(./sls/config/env.yml)}

package:
  individually: true

custom:
  cognito:
    PollName: ${self:service}-${self:provider.stage}-UserPool

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(./sls/functions/auth.yml)}

resources:
  - ${file(./sls/resources/UserPool.yml)}
