org: williamdnts
service: foodiary-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs24.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}

package:
  individually: true

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  hello:
    handler: src/main/functions/hello.handler
    events:
      - httpApi:
          path: /hello/{id}
          method: POST

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-UserPool
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-${self:provider.stage}-UserPoolClient
        UserPoolId: !Ref UserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
        TokenValidityUnits:
          AccessToken: hours
        AccessTokenValidity: 12
        RefreshTokenRotation:
          Feature: ENABLED
          RetryGracePeriodSeconds: 0


