org: williamdnts
service: foodiary-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs24.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}

package:
  individually: true

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(./sls/functions/auth.yml)}

resources:
  - ${file(./sls/resources/UserPool.yml)}
